# Generated by Django 4.2.2 on 2024-07-26 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_order_product_remove_order_quantity_orderitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=20)),
                ("payload_capacity", models.PositiveIntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("grams", "Grams"), ("kg", "KiloGrams")], max_length=5
                    ),
                ),
                ("battery_life", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("on flight", "On Flight"),
                            ("out of service", "Out of  Service"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("processing", "Processing"),
                    ("delivered", "Delivered"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "drone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.drone",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.order",
                    ),
                ),
            ],
        ),
    ]
