# Generated by Django 4.2.2 on 2024-07-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="user",
        ),
        migrations.AddField(
            model_name="otp",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
